apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: previews
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: sl-app
  source:
    repoURL: https://github.com/sl-ahmedfourti/sl-app.git
    targetRevision: HEAD
    path: preview
  destination:
    server: https://kubernetes.default.svc
    namespace: previews-sl-app
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true