---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: slapp
  namespace: argocd
spec:
  destination:
    name: in-cluster
  source:
    helm:
      values: |
        replicaCount: 2
        service:
          type: ClusterIP