---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: slapp
  namespace: sl-app
spec:
  destination:
    name: in-cluster
  source:
    helm:
      values: |
        replicaCount: 1