---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: slapp
  namespace: argocd
spec:
  destination:
    namespace: sl-app-nonprod
    name: nonprod
  source:
    helm:
      values: |
        replicaCount: 1
        service:
          type: ClusterIP