---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: pr-sl-app-feature-shopping
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: pr-sl-app-feature-shopping
  project: sl-app
  source:
    helm:
      values: |
        image:
          tag: "2.6.2"
        replicaCount: 2
      version: v3
    path: preview
    repoURL: https://github.com/sl-ahmedfourti/sl-app.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
