apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{.PR_NAME}}"
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: sl-app
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: nginx
    targetRevision: 9.7.5
    helm:
      values: |
        image:
          tag: "{{.IMAGE_TAG}}"
        replicaCount: 2
      version: v3
  destination:
    namespace: "{{.PR_NAME}}"
    name: nonprod
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true