apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: slapp
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
  project: sl-app
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: nginx
    targetRevision: 9.7.5
    helm:
      releaseName: nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true