---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: slapp-prod
  # cascade deletes
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: sl-app

  source:
    repoURL: https://github.com/sl-ahmedfourti/sl-app.git
    targetRevision: HEAD
    path: stages/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: slapp-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true