apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -prod

helmCharts:
  - name: nginx
    repo: https://charts.bitnami.com/bitnami
    version: 9.7.5
    releaseName: nginx
    namespace: slapp-prod
    valuesFile: values-prod.yaml